name: animated_icon
description: This package support a animated icon with some customization like color, animate, hover, callback.
version: 0.0.4
repository: https://github.com/Mindinventory/animated_icons

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  assets:
    - assets/
